/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   cuba-app-aware-behavior.html
 */

interface CubaAppAwareBehavior {
  readonly app: cuba.CubaApp|null;
  appName: string|null|undefined;
  _appNameChanged(appName: any): void;
}

declare const CubaAppAwareBehavior: object;
