/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   cuba-js-script.html
 */

/// <reference path="../cuba-rest-js/dist-browser/cuba.d.ts" />