/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   cuba-localize-behavior.html
 */

/// <reference path="cuba-app-aware-behavior.d.ts" />

interface CubaLocalizeBehavior {
  useKeyIfMissing: boolean|null|undefined;
  enums: object|null|undefined;
  messages: object|null|undefined;
  serverMessages: object|null|undefined;
  readonly msg: Function|null|undefined;
  readonly enumValues: Function|null|undefined;
  attached(): void;
  detached(): void;
}

declare const CubaLocalizeBehavior: object;
